name: Manual Testing

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  create-status:
    runs-on: ubuntu-latest
    steps:
      - name: Create a manual testing status - pending
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: 'pending',
              context: 'Manual Testing',
              description: 'Manual testing is in progress'
            })
      - name: Wait for manual testing to complete
        run: sleep 25m
      - name: Create a manual testing status - success
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: 'success',
              context: 'Manual Testing',
              description: 'Manual testing has passed'
            })
